### ISSUE TITLE
About Spatial Attention

### ISSUE THREAD

**Issue by LionRoarRoar** [DaoyiG/TC-Depth#6]
Hi, thank you for your work. I have some questions about the spatial attention layer.

Q1: In Eq.3, the definition of denominator is not clear enough. Is it the maximum or variance？
Q2: How to get the rough depth for spatial attention calculation?  Do we need to re-inference the network?
Q3: It seems that your spatial-temporoal attention is a cascade of spatial attention and temporal attention module, right?

**Comment by HanzhiC** [comment]
Hi, thanks for the interest.
A1: this is the variance (hyperparam to be set.)
A2: No need of re-inference, because we have a shallow decoder (several shallow conv layers) to decode the lowest resolution feature from the encoder to acquire a rough depth, then detach this depth and use such depth to establish spatial attention.
A3: Yes. We apply it 3 times.
